config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :products, :path => "/admin/dashboard/products"
  resources :brands, :path => "/admin/dashboard/brands"
  resources :categories, :path => "/admin/dashboard/categories"

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
    belongs_to :product
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    belongs_to :brand

    has_many :assets

    def list
        Product.list(max:20)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|

      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        respond_to do |format|
            format.html { redirect_to welcome_url, notice: 'User was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

end

app/controllers/products_controller.rb
require 'utilities/s3_asset_service'

class ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.brand = Brand.find params[:brand]
    @product.category = Category.find params[:category]
    if params[:files]
        add_image(params)
    end
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    if params[:files]
        add_image(params)
    end
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :sku, :price, :count)
    end

    def add_image(params)
        s3AssetService = S3AssetService.instance
        params[:files].each do | file |
            image_info_s3 = s3AssetService.upload_image_to_s3(file)
            asset = s3AssetService.save_s3Asset_info("http://bikespeed.s3.amazonaws.com/#{image_info_s3.key}")
            @product.assets << asset
            @product.save
        end
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brands/_form.html.erb
<%= form_for(brand) do |f| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1>Bikespeed custom Cycles</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikespeed Custom Cycles</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <p class="navbar-text pull-right">
   </p>
        <!-- Navbar (sit on top) -->
        <div class="w3-top">
            <div class="w3-bar w3-white w3-wide w3-padding w3-card-2">
                <%= link_to '<b>BIKESPEED</b> Custom Cycle'.html_safe, root_path, :class=> 'w3-bar-item w3-button' %>
                <!-- Float links to the right. Hide them on small screens -->
                <div class="w3-right w3-hide-small">
                    <a href="#projects" class="w3-bar-item w3-button">Productos</a>
                    <a href="#about" class="w3-bar-item w3-button">About</a>
                    <a href="#contact" class="w3-bar-item w3-button">Contact</a>
                    <% if user_signed_in? %>
                        Logged in as <strong><%= current_user.email %></strong>.
                        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'w3-bar-item w3-button' %> |
                        <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'w3-bar-item w3-button'  %>
                    <% else %>
                        <%= link_to "Sign up", new_user_registration_path, :class => 'w3-bar-item w3-button'  %> |
                        <%= link_to "Login", new_user_session_path, :class => 'w3-bar-item w3-button'  %>
                    <% end %>

                </div>
            </div>
        </div>



        <%= yield %>
        <footer class="w3-center w3-black w3-padding-16">
            <div class="w3-col l3 m6 w3-margin-bottom">
            </div>
            <div class="w3-col l3 m6 w3-margin-bottom">
                <ul class="company-social">
                    <li class="social-facebook"><a href="https://www.facebook.com/bikespeed.customcycles" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    <li class="social-twitter"><a href="https://twitter.com/bikespeed1" target="_blank"><i class="fa fa-twitter"></i></a></li>
                    <li class="social-vimeo"><a href="https://instagram.com/bikespeed/" target="_blank"><i class="fa fa-instagram"></i></i></a></li>
                </ul>
            </div>
        </footer>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for product, :html => {:multipart => true} do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :count %>
    <%= f.text_field :count %>
  </div>

  <div class="field">
      <label>Brand</label>
      <%= select_tag 'brand', options_from_collection_for_select(Brand.all, :id,:name) =%>
  </div>

  <div class="field">
      <label>category</label>
      <%= select_tag 'category', options_from_collection_for_select(Category.all, :id, :name) =%>
  </div>
    <div class="field">
            <%= file_field_tag 'files[]',:multiple => true %>
                  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Sku</th>
      <th>Price</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.sku %></td>
        <td><%= product.price %></td>
        <td><%= product.count %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Count:</strong>
  <%= @product.count %>
</p>


<% @product.assets.each do | asset | %>
    <%= image_tag(asset.url_file) %>
<% end %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
    <body>
        <!-- Header -->
        <header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
            <img class="w3-image" src="http://bikespeed.s3.amazonaws.com/specialized.png?AWSAccessKeyId=AKIAJSHGYFLR3S2FL7UQ&Expires=1502068682&Signature=NUlxacPNYtUVbMUNW0rG1JcoC04%3D" alt="Architecture" width="100%" height="40%">
            <div class="w3-display-middle w3-margin-top w3-center">
                <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>BI</b></span> <span class="w3-hide-small w3-text-light-grey">kespeed</span></h1>
            </div>
        </header>
        <!-- Page content -->
        <div class="w3-content w3-padding" style="max-width:1564px">

            <!-- Project Section -->
            <div class="w3-container w3-padding-32" id="projects">
                <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Productos</h3>
            </div>

            <div class="w3-row-padding">
                <% Product.all.each do | producto | %>
                    <div class="w3-col l3 m6 w3-margin-bottom">
                        <div class="w3-display-container">
                            <div class="w3-display-topleft w3-black w3-padding"><%= producto.name %></div>
                            <%= image_tag(producto.assets.first.url_file, style: "width:100%" ) %>
                        </div>
                    </div>
                <% end %>

            </div>

            <div class="w3-row-padding">
                <div class="w3-col l3 m6 w3-margin-bottom">
                    <div class="w3-display-container">
                        <div class="w3-display-topleft w3-black w3-padding">Summer House</div>
                        <img src="/w3images/house2.jpg" alt="House" style="width:99%">
                    </div>
                </div>
                <div class="w3-col l3 m6 w3-margin-bottom">
                    <div class="w3-display-container">
                        <div class="w3-display-topleft w3-black w3-padding">Brick House</div>
                        <img src="/w3images/house5.jpg" alt="House" style="width:99%">
                    </div>
                </div>
                <div class="w3-col l3 m6 w3-margin-bottom">
                    <div class="w3-display-container">
                        <div class="w3-display-topleft w3-black w3-padding">Renovated</div>
                        <img src="/w3images/house4.jpg" alt="House" style="width:99%">
                    </div>
                </div>
                <div class="w3-col l3 m6 w3-margin-bottom">
                    <div class="w3-display-container">
                        <div class="w3-display-topleft w3-black w3-padding">Barn House</div>
                        <img src="/w3images/house3.jpg" alt="House" style="width:99%">
                    </div>
                </div>
            </div>

            <!-- About Section -->
            <div class="w3-container w3-padding-32" id="about">
                <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">About</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint
                occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                laboris nisi ut aliquip ex ea commodo consequat.
                </p>
            </div>

            <div class="w3-row-padding w3-grayscale">
                <div class="w3-col l3 m6 w3-margin-bottom">
                    <img src="/w3images/team2.jpg" alt="John" style="width:100%">
                    <h3>John Doe</h3>
                    <p class="w3-opacity">CEO & Founder</p>
                    <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
                    <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
                </div>
                <div class="w3-col l3 m6 w3-margin-bottom">
                    <img src="/w3images/team1.jpg" alt="Jane" style="width:100%">
                    <h3>Jane Doe</h3>
                    <p class="w3-opacity">Architect</p>
                    <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
                    <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
                </div>
                <div class="w3-col l3 m6 w3-margin-bottom">
                    <img src="/w3images/team3.jpg" alt="Mike" style="width:100%">
                    <h3>Mike Ross</h3>
                    <p class="w3-opacity">Architect</p>
                    <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
                    <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
                </div>
                <div class="w3-col l3 m6 w3-margin-bottom">
                    <img src="/w3images/team4.jpg" alt="Dan" style="width:100%">
                    <h3>Dan Star</h3>
                    <p class="w3-opacity">Architect</p>
                    <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
                    <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
                </div>
            </div>

            <!-- Contact Section -->
            <div class="w3-container w3-padding-32" id="contact">
                <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Contact</h3>
                <p>Lets get in touch and talk about your and our next project.</p>
                <form action="/action_page.php" target="_blank">
                    <input class="w3-input" type="text" placeholder="Name" required name="Name">
                    <input class="w3-input w3-section" type="text" placeholder="Email" required name="Email">
                    <input class="w3-input w3-section" type="text" placeholder="Subject" required name="Subject">
                    <input class="w3-input w3-section" type="text" placeholder="Comment" required name="Comment">
                    <button class="w3-button w3-black w3-section" type="submit">
                        <i class="fa fa-paper-plane"></i> SEND MESSAGE
                    </button>
                </form>
            </div>

            <!-- End page content -->
        </div>

        <!-- Google Map -->
        <div id="googleMap" class="w3-grayscale" style="width:100%;height:450px;"></div>

        <!-- Footer -->

        <!-- Add Google Maps -->
        <script>
function myMap()
{
    myCenter=new google.maps.LatLng(41.878114, -87.629798);
    var mapOptions= {
        center:myCenter,
        zoom:12, scrollwheel: false, draggable: false,
        mapTypeId:google.maps.MapTypeId.ROADMAP
    };
    var map=new google.maps.Map(document.getElementById("googleMap"),mapOptions);

    var marker = new google.maps.Marker({
        position: myCenter,
    });
    marker.setMap(map);
}
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap"></script>
        <!--
            To use this code on your website, get a free API key from Google.
            Read more at: https://www.w3schools.com/graphics/google_maps_basic.asp
        -->

    </body>
</html>